name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Confirm repository contents
        run: |
          echo "GitHub Actions is running!"
          echo "Repository contents:"
          ls